### PR TITLE
Fix chronometer refresh incorrectly reading the long argument sleep time

### LINKED ISSUE #2703: pihole chronometer --refresh
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

8

---
**Expected behaviour:**

i would like don't see:
sleep: option not valid -- "-"
Try 'sleep --help' for more information.

**Actual behaviour:**

immagine

**Steps to reproduce:**

when i digit from CLI  pihole chronometer --refresh, there's an error on sleep command

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

### PR DESCRIPTION
**Pull request by Mcat12**
**By submitting this pull request, I confirm the following:** 
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
---
**What does this PR aim to accomplish?:**
Fixes #2703

**How does this PR accomplish the above?:**
`-r` worked, but `--refresh` did not. The parsing of the argument was fixed to support both forms.

**What documentation changes (if any) are needed to support this PR?:**
None

### CODE REVIEW

File: advanced/Scripts/chronometer.sh [hunk 1]
```diff
@@ -463,8 +463,7 @@ chronoFunc() {
         # Get refresh number
         if [[ "$*" == *"-r"* ]]; then
             num="$*"
-            num="${num/*-r /}"
-            num="${num/ */}"
+            num="${num/*-r* /}"
```
Comment (PromoFaux) [inline advanced/Scripts/chronometer.sh]: Will this equally allow for something like `--railway`?

Comment (Mcat12) [reply advanced/Scripts/chronometer.sh]: I believe so. The argument parsing needs work overall, and should probably be done in a separate PR. Previously it would have also recognized that argument as a refresh argument.

Comment (PromoFaux) [reply advanced/Scripts/chronometer.sh]: I'm happy with this as is for a quick fix., will approve!

But I guess we should be doing it more like this? https://github.com/pi-hole/pi-hole/blob/master/pihole#L446

Comment (Mcat12) [reply advanced/Scripts/chronometer.sh]: The issue here seems to be that we allow many different flags, and have a hard time extracting the associated value from the arguments. `pihole` only takes in one sub-command, so it has an easier time. It may be that chronometer should also only take in one command, but it's written to allow multiple.

Comment (dschaper) [reply advanced/Scripts/chronometer.sh]: I'll approve as well, but I'll go on record that this is a very bad way of handling flags.

Comment (Mcat12) [reply advanced/Scripts/chronometer.sh]: It looks like chronometer actually will prevent those other invalid flags eariler:
```
$ pihole -c --railway 1
Unknown option. Please view 'pihole -c --help' for more information
```

I've pushed a commit to make this explicit here, though.
