### PR TITLE
Don't show web version in pihole -v output if not installed

### LINKED ISSUE #2546: pihole -v without website/admin interface returns error
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
pihole -v should return the version numbers of all the installed features.

**Actual behaviour:**
Without the website/admin interface installed, it returns an error when trying to show the admin version:
```
#pihole -v    
Pi-hole version is v4.1 (Latest: v4.1)  
fatal: Not a git repository (or any of the parent directories): .git    
AdminLTE version is ERROR (Latest: v4.1)    
FTL version is v4.1 (Latest: v4.1) 
```

**Steps to reproduce:**
Install pihole without website/admin pieces, then run pihole -v

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
None taken

**Troubleshooting undertaken, and/or other relevant information:**
No attempt to fix, does not actually break anything but only looks confusing.

### PR DESCRIPTION
**Pull request by Mcat12**
**By submitting this pull request, I confirm the following:** 
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
---
**What does this PR aim to accomplish?:**
Fix #2546 

**How does this PR accomplish the above?:**
Only run the web version check if the web interface has been installed.

**What documentation changes (if any) are needed to support this PR?:**
None

### CODE REVIEW

File: advanced/Scripts/version.sh [hunk 1]
```diff
@@ -136,8 +136,16 @@ errorOutput() {
 }
 
 defaultOutput() {
+    # Source the setupvars config file
+    # shellcheck disable=SC1091
+    . /etc/pihole/setupVars.conf
```
Comment (dschaper) [inline advanced/Scripts/version.sh]: `.` can be ambiguous and misinterpreted. 

```suggestion
     source /etc/pihole/setupVars.conf
```
