### PR TITLE
Let Chronometer query all data from FTL directly

### LINKED ISSUE #1305: [BUG] Commandline pihole -c does not calculate on system w/o web interface.
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[BUG] Expected Behaviour:**
 ```pihole -c``` Calculates stats and displays to an LCD (or terminal ??)

**[BUG | ISSUE] Actual Behaviour:**
```
 ___ _     _        _
| _ (_)___| |_  ___| |___
|  _/ |___| ' \/ _ \ / -_)
|_| |_|   |_||_\___/_\___|

        0.0.0.0

 load average: 0,02, 0,07, 0,08
2 days, 8 hours, 58 minutes.
-------------------------------
Blocking:      0
Queries:       0
Pi-holed:      0 (0.00%)
^C
me@rpiii:~ wc -l /var/log/pihole.log
9524 /var/log/pihole.log
me@rpiii:~ $ cat /var/log/pihole.log |grep 0.0.0.0 |tail
Mar  6 19:08:35 dnsmasq[14520]: /etc/pihole/gravity.list collector.githubapp.com is 0.0.0.0
Mar  6 19:08:37 dnsmasq[14520]: /etc/pihole/gravity.list www.google-analytics.com is 0.0.0.0
Mar  6 19:11:12 dnsmasq[14520]: /etc/pihole/gravity.list livepassdl.conviva.com is 0.0.0.0
Mar  6 19:16:12 dnsmasq[14520]: /etc/pihole/gravity.list livepassdl.conviva.com is 0.0.0.0
Mar  6 19:17:27 dnsmasq[14520]: /etc/pihole/gravity.list collector.githubapp.com is 0.0.0.0
Mar  6 19:17:27 dnsmasq[14520]: /etc/pihole/gravity.list www.google-analytics.com is 0.0.0.0
Mar  6 19:17:27 dnsmasq[14520]: /etc/pihole/gravity.list www-google-analytics.l.google.com is 0.0.0.0
Mar  6 19:19:48 dnsmasq[14520]: /etc/pihole/gravity.list collector.githubapp.com is 0.0.0.0
Mar  6 19:21:12 dnsmasq[14520]: /etc/pihole/gravity.list livepassdl.conviva.com is 0.0.0.0
Mar  6 19:26:12 dnsmasq[14520]: /etc/pihole/gravity.list livepassdl.conviva.com is 0.0.0.0
me@rpiii:~ $
```
I guess there will be no calculations without the _api.php_ as is the case on a system where the webinterface was **not** installed.
This might change when FTL goes live ??

**[BUG] Steps to reproduce:**

use the CLI command ```pihole -c``` on system that was installed without the admin web interface.

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---

Let Chronometer query all data from FTL (removes need for having the web interface with its API installed)
Fixes #1305

```
pi@raspberrypi:/etc/.pihole# pihole -c
 ___ _     _        _
| _ (_)___| |_  ___| |___
|  _/ |___| ' \/ _ \ / -_)
|_| |_|   |_||_\___/_\___|

        192.168.2.10/24

 load average: 0,01, 0,04, 0,01
2 days, 4 hours, 1 minutes.
-------------------------------
Recently blocked:
  www.googleadservices.com
Blocking:      103.563
Queries:       23.510
Pi-holed:      2.303 (10%)
```

We even generate JSON output for other programs that want to use it
```
pi@raspberrypi:/etc/.pihole# pihole -c -j
{"domains_being_blocked":103563,"dns_queries_today":23510,"ads_blocked_today":2303,"ads_percentage_today":9.795832}
```

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by PromoFaux** [comment]
Approved

File: advanced/Scripts/chronometer.sh [hunk 1]
```diff
@@ -8,34 +8,55 @@
...
+	ads_blocked_today_raw=$(grep "ads_blocked_today" <<< "$summary" | grep -Eo "[0-9]+$")
+	ads_blocked_today=$(printf "%'.f" ${ads_blocked_today_raw})
+	ads_percentage_today_raw=$(grep "ads_percentage_today" <<< "$summary" | grep -Eo "[0-9.]+$")
+	LC_NUMERIC=C ads_percentage_today=$(printf "%'.f" ${ads_percentage_today_raw})
 }
 
 normalChrono() {
 	for (( ; ; )); do
+		get_summary_data
+		domain=$(GetFTLData recentBlocked)
```
Comment (Mcat12) [inline advanced/Scripts/chronometer.sh]: This line seems to be duplicated on line 73.

Comment (DL6ER) [inline advanced/Scripts/chronometer.sh]: You are right, I will look at that tomorrow.
