### PR TITLE
Fix issue with multipe default gateways when running the debug

### LINKED ISSUE #4019: piholeDebug.sh Multiple Interfaces leads to ping failure
This is the first issue I am opening on github, so please be kind, if I make a mistake :-)

### Versions
- Pi-hole:  v5.2.4
- AdminLTE:  v5.3.1
- FTL:  v5.5.1

### Platform
- OS and version:  Raspbian GNU/Linux 10
- Platform:  Raspberry Pi

### Expected behavior

When executing ``` pihole -d ``` I expect, that the default Gateway is pingable, but i get an error as shown below.

### Actual behavior / bug

```
[i] Default IPv4 gateway: 10.0.0.1
10.0.0.1
   * Pinging 10.0.0.1
10.0.0.1...
ping: 10.0.0.1
10.0.0.1: Name or service not known
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)

[i] Default IPv6 gateway: fe80::7eff:4dff:fef1:22c8
fe80::7eff:4dff:fef1:22c8
   * Pinging fe80::7eff:4dff:fef1:22c8
fe80::7eff:4dff:fef1:22c8...
ping: fe80::7eff:4dff:fef1:22c8
fe80::7eff:4dff:fef1:22c8: Name or service not known
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)
```

### Steps to reproduce

This error occures, if you have two interfaces and thus two default gateways.
```
>pi@pihole:~$ ip -4 route
default via 10.0.0.1 dev eth0 src 10.0.0.30 metric 202
default via 10.0.0.1 dev wlan0 proto dhcp src 10.0.0.39 metric 303
10.0.0.0/24 dev eth0 proto dhcp scope link src 10.0.0.30 metric 202
10.0.0.0/24 dev wlan0 proto dhcp scope link src 10.0.0.39 metric 303
```

## Debug Token
Not possible: 
```
>pi@pihole:~$ `pihole -d`. https://docs.pi-hole.net/core/pihole-command/#debugger
ping: 10.0.0.1
10.0.0.1: Name or service not known
ping: fe80::7eff:4dff:fef1:22c8
fe80::7eff:4dff:fef1:22c8: Name or service not known
[?] Would you like to upload the log? [y/N] y
-bash: $'\E[H\E[J\E[3JThis': command not found
```

### Additional context
the Problem is that the Ping Command in the follwing line 
https://github.com/pi-hole/pi-hole/blob/cbfb58f7a283c2a3e7aad95a834a0287175ccb24/advanced/Scripts/piholeDebug.sh#L708
resolves to: ```ping -c 1 -W 2 -n 10.0.0.1 10.0.0.1 -I eth0 ```, as I have two interfaces plugged an thus two default gateways. 

I might have a fix for this issue, as you could change 
https://github.com/pi-hole/pi-hole/blob/cbfb58f7a283c2a3e7aad95a834a0287175ccb24/advanced/Scripts/piholeDebug.sh#L698
to 
```
gateway="$(ip -"${protocol}" route | grep default | grep ${PIHOLE_INTERFACE} | cut -d ' ' -f 3)"
```

### PR DESCRIPTION
**Pull request by Flashbang007**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Fix issue with multipe default gateways when running the debug (```pihole -d```). It results in a ping failure 

Fixes #4019 

**How does this PR accomplish the above?:**
To filter the specific pihole configured device I woul add ```| grep ${PIHOLE_INTERFACE} | ``` to: 
https://github.com/pi-hole/pi-hole/blob/cbfb58f7a283c2a3e7aad95a834a0287175ccb24/advanced/Scripts/piholeDebug.sh#L698

**What documentation changes (if any) are needed to support this PR?:**

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

File: advanced/Scripts/piholeDebug.sh [hunk 1]
```diff
@@ -695,7 +695,7 @@ ping_gateway() {
     # Check if we are using IPv4 or IPv6
     # Find the default gateway using IPv4 or IPv6
     local gateway
-    gateway="$(ip -"${protocol}" route | grep default | cut -d ' ' -f 3)"
+    gateway="$(ip -"${protocol}" route | grep default | grep "${PIHOLE_INTERFACE}" | cut -d ' ' -f 3)"
```
Comment (Flashbang007) [inline advanced/Scripts/piholeDebug.sh:698]: It filters the specific pihole configured interface. so no ambiguous output will result in a ping failure.

**Comment by dschaper** [comment]
Thanks! Looks good!

**Review by dschaper — APPROVED** [review]
