### PR TITLE
Wipe version file before creating a new one

### LINKED ISSUE #6362: Version inconsistencies during updates
### Versions

- Pi-hole:  Core version is v5.17.2 (Latest: v6.1.4)
- Web:  Web version is v6.2.1 (Latest: v6.2.1)
- FTL:  FTL version is v6.2.3 (Latest: v6.2.3)

### Platform

- OS and version:  PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
- 
### Expected behavior

Web UI shows correct installed system versions.

### Actual behavior / bug

Web UI shows partial version information.
Core N/A · Update available! FTL v6.2.3Web interface v6.2.1

### Steps to reproduce

Ran sudo pihole -up and got this output:
pi@pihole:~ $ sudo pihole -up
  [✓] Building dependency package pihole-meta.deb
  [✓] Installing Pi-hole dependency package

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

### LINKED ISSUE #6527: Core version will not update
### Versions

```
Core version is v5.18.4 (Latest: v6.3)
Web version is v6.4 (Latest: v6.4)
FTL version is v6.4.1 (Latest: v6.4.1)
```

### Platform

- OS and version:  Debian 11

- Platform:  Raspberry Pi

### Expected behavior

The core version to update to the latest.

### Actual behavior / bug

My core is at v5.18.4, but updating via `pihole -up` has no effect on it.

### Steps to reproduce

```
pi@raspberrypi:~ $ sudo pihole -up
  [✓] Building dependency package pihole-meta.deb
  [✓] Installing Pi-hole dependency package

  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		up to date

  [✓] Everything is up to date!

pi@raspberrypi:~ $ pihole -v
Core version is v5.18.4 (Latest: v6.3)
Web version is v6.4 (Latest: v6.4)
FTL version is v6.4.1 (Latest: v6.4.1)
```

## Debug Token

- URL:  https://tricorder.pi-hole.net/JrqqsNfl/

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

We are using `/etc/pihole/versions` to store local and remote version of Pi-hole's components to populate the web interface and `pihole -v`.
Lately we have seen some reports (eg. [here](https://github.com/pi-hole/pi-hole/issues/6527), [here](https://github.com/pi-hole/pi-hole/issues/6362)) where running `pihole updatechecker` was not sufficient to fix incorrect version information in the file, but a removal was needed (interestingly, file size was always too large).

This PR removes the old version file before creating a new one every time `pihole updatechecker` runs.

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.2)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by rdwebdesign — DISMISSED** [review]

File: advanced/Scripts/updatecheck.sh [hunk 1]
```diff
@@ -50,9 +50,10 @@ rm -f "/etc/pihole/GitHubVersions"
 rm -f "/etc/pihole/localbranches"
 rm -f "/etc/pihole/localversions"
 
-# Create new versions file if it does not exist
 VERSION_FILE="/etc/pihole/versions"
-touch "${VERSION_FILE}"
+
+# Truncates the file to zero length if it exists to clear it up, otherwise creates an empty file.
+truncate -s 0 "${VERSION_FILE}"
```
Comment (casperklein) [inline advanced/Scripts/updatecheck.sh:56]:
```suggestion
: > "${VERSION_FILE}"
```
This works too and is bash only.

**Comment by casperklein** [comment]
> interestingly, file size was always too large

Just out of curiosity, do you know the file's content? That could give a hint, what the root cause of this problem is.

File: advanced/Scripts/updatecheck.sh (hunk 1 above)
Comment (yubiuser) [reply advanced/Scripts/updatecheck.sh:56]: This will work, but personally I would prefer to keep 'truncate' as is much easier to read the source code and unterstand it. In 6 month will need to remember what ': >' does.

**Comment by yubiuser** [comment]
It was always around doubled file size (600+ bytes). We suspect it might be a race condition between the 'touch' in `updatechecker.sh` and the one in `utils.sh` when we used its `addOrEditKeyValPair`

**Review by PromoFaux — APPROVED** [review]
