### PR TITLE
Ensure gravity_Cleanup() checks the correct directory

### LINKED ISSUE #6075: When adlist is removed from gravity the corresponding list data is not removed from /etc/pihole/listsCache/
### Versions
Core
    Version is v6.0.5-13-g387ec3a3 (Latest: null)
    Branch is development
    Hash is 387ec3a3 (Latest: 387ec3a3)
Web
    Version is v6.0.2-51-g0e41aaa4 (Latest: null)
    Branch is development
    Hash is 0e41aaa4 (Latest: 0e41aaa4)
FTL
    Version is vDev-464b2df (Latest: null)
    Branch is development
    Hash is 464b2dfc (Latest: 464b2dfc)

### Platform
- OS and version:  Ubuntu 24.04.2
- Platform:   Raspberry Pi 4 Model B Rev 1.1

### Expected behavior

when a list is removed from gravity the corresponding list info should be removed from `/etc/pihole/listsCache/` 

### Actual behavior / bug

when a list is removed from gravity the corresponding list info is _not_ removed from `/etc/pihole/listsCache/` 

### Steps to reproduce

1. Go to https://pi.hole/admin/groups/lists
2. ad a few lists 
3. update gravity
4. check `/etc/pihole/listsCache/` and see newly added list info 
5. go back to https://pi.hole/admin/groups/lists 
6. remove the newly added lists
7. update gravity again
8. go back to check `/etc/pihole/listsCache/` again and see list info for lists that were just removed 

## Debug Token

- URL:  [✓] Your debug token is: https://tricorder.pi-hole.net/ogB9Gfk6/

### PR DESCRIPTION
**Pull request by mwoolweaver**
**What does this PR aim to accomplish?:**

ensure `gravity_Cleanup()` checks the correct directory (`listsCacheDir`) for list data when it's `Cleaning up stray matter`. 

**How does this PR accomplish the above?:**

changes 

https://github.com/pi-hole/pi-hole/blob/8797a0df05121225802508a0022543ccee9c47be/gravity.sh#L938

to check `listsCacheDir` instead of `piholeDir` for list data as the location was changed in #5869

also glob (`*`) here 
https://github.com/pi-hole/pi-hole/blob/8797a0df05121225802508a0022543ccee9c47be/gravity.sh#L941

with `"${file}"*` to remove `.etag` & `.sha1` as well.

should fix #6075 

**Link documentation PRs if any are needed to support this PR:**

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [✔] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

File: gravity.sh [hunk 1]
```diff
@@ -935,10 +935,10 @@ gravity_Cleanup() {
   # Ensure this function only runs when gravity_SetDownloadOptions() has completed
```
Comment (yubiuser) [inline gravity.sh:935]:
```suggestion
  # Ensure this function only runs when gravity_DownloadBlocklists() has completed
```

File: gravity.sh [hunk 2]
```diff
@@ -935,10 +935,10 @@ gravity_Cleanup() {
...
   if [[ "${gravity_Blackbody:-}" == true ]]; then
```
Comment (yubiuser) [inline gravity.sh:936]:
```suggestion
  if [[ "${DownloadBlocklists_done:-}" == true ]]; then
```

File: gravity.sh [hunk 3]
```diff
@@ -935,10 +935,10 @@ gravity_Cleanup() {
...
     # Remove any unused .domains files
```
Comment (yubiuser) [inline gravity.sh:937]:
```suggestion
    # Remove any unused .domains/.etag/.sha files
```

File: gravity.sh [hunk 4]
```diff
@@ -935,10 +935,10 @@ gravity_Cleanup() {
...
-    for file in "${piholeDir}"/*."${domainsExtension}"; do
+    for file in "${listsCacheDir}"/*."${domainsExtension}"; do
       # If list is not in active array, then remove it
```
Comment (yubiuser) [inline gravity.sh:939]:
```suggestion
      # If list is not in active array, then remove it and all associated files
```

**Review by yubiuser — CHANGES_REQUESTED** [review]
Thanks for your PR. 
We try to get rid of the "funny" names to make the complex script more readable. Could you please change the other occurrence of `gravity_Blackbody`  as well
