### PR TITLE
Install 32bit FTL on 32bit OS (even if 64bit architecture is detected)

### LINKED ISSUE #1998: Unable to install / upgrade pi-hole on 64bit machine with a 32bit OS
Edited:
**In raising this issue, I confirm the following:**
    [x] I have read and understood the contributors guide.
    [x] The issue I am reporting can be replicated.
    [x] The issue I am reporting isn't a duplicate (see FAQs, closed issues, and open issues).

**How familiar are you with the source code relevant to this issue?:** 1

**Expected behaviour:** Able to install/upgrade pi-hole without errors.

**Actual behaviour:** Setup terminates without fully going through the full setup. The installation then is corrupted.

**Steps to reproduce:**
1) Download raspberry Pi Desktop from https://www.raspberrypi.org/downloads/raspberry-pi-desktop/ and install onto PC/virtual machine
2) Run "sudo apt-get update"
3) Run "sudo apt-get upgrade"
4) Run "sudo reboot"
5) Once back online, run pi-hole installer "curl -sSL https://install.pi-hole.net | bash"

**Debug token provided by uploading pihole -d log:** bsglqnpute

**Troubleshooting undertaken, and/or other relevant information:**
I have tried reinstalling raspberry Pi Desktop a few times - same issue
I have tried both the "One-Step Automated Install" and the "Method 1: Clone our repository and run" methods but both fail

_----Previous----
Hello Pi-Hole Team,
I would like to report an issue with the installer running on raspbian OS. The setup gets as far as "Starting dnsmasq service..." then the setup terminates without further errors or warning. Pi-Hole will not load and has corrupted the install. I have restored the OS back and tried again both using the auto install (curl -sSL https://install.pi-hole.net  | bash) and the "Method 1: Clone our repository and run" way but both are doing the same thing. I have run apt-get update / upgrade before the install and also tried sudo -i before running the bash install but no effect. Can you please help/update the installer? I have attached a print screen.
pihole
Kind Regards._

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**

Try to determine if the user is running a 32bit OS on a 64bit system. If so, download the 32bit binary as we cannot expect the 64bit libraries to be present.

Should fix #1998 and many others + some issues we saw on Discourse.

**How does this PR accomplish the above?:**

Try to detect architecture `dpkg` uses to install packages. This will only work on Debian-based systems, but not on Fedora, etc.

Unfortunately, I cannot really test this at the moment as droplets with 32bit OS return
```
$ uname -m
i686
```
(which already leads to downloading the 32 bit library)

---

* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pihole-installer-usr-bin-pihole-ftl-no-such-file-or-directory/6006/34

File: advanced/Scripts/piholeCheckout.sh [hunk 1]
```diff
@@ -68,9 +68,20 @@ FTLinstall() {
 }
 
 get_binary_name() {
+  # This gives the machine architecture which may be different from the OS architecture...
   local machine
   machine=$(uname -m)
 
+  # This gives the architecture of packages dpkg installs (for example, "i386")
+  local dpkgarch
+  dpkgarch=$(dpkg --print-architecture 2> /dev/null)
```
Comment (Mcat12) [inline advanced/Scripts/piholeCheckout.sh]: On fedora, is it ok that dpkg will not exist?

Comment (rrobgill) [reply advanced/Scripts/piholeCheckout.sh]: dpkg won't be there, but file will be:

```
file $(whereis file) | grep -v "64-bit" | grep "32-bit" &> /dev/null
if [ "$?" = 0 ]; then
  machine="i686"
fi

```
Which would technically work in both debian and fedora universes. But I'd only use it if 1] dpkg wasn't available, and 2] the architecture was identifying as x86_64 via uname -m.
