### PR TITLE
FTL always determined.

### LINKED ISSUE #2986: Updating only FTL does not update the binary variable and thus fails
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

7

---
**Expected behaviour:**

Succesful update

**Actual behaviour:**

```
pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] FTL:              update available

  [i] FTL out of date

  [i] FTL Checks...

  [i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404 Not Found
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/FTL/releases/download/v4.3.1/tbd not found
```

**Steps to reproduce:**

`pihole -up` without up to date FTL

**Troubleshooting undertaken, and/or other relevant information:**

Added `get_binary_name` to line 2193 of 'automated install/basic-install.sh'.

### PR DESCRIPTION
**Pull request by dschaper**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Fixes #2986 #2970 #2636

**How does this PR accomplish the above?:**
Binary name is stored in a temporary file in the download directory. Global placeholder of `tbd` is removed. 

This is a semi-stopgap fix that will work until a more proper fix can be applied.

### CODE REVIEW

File: advanced/Scripts/piholeCheckout.sh [hunk 1]
```diff
@@ -46,6 +46,10 @@ checkout() {
     local corebranches
     local webbranches
 
+    local binary
+    get_binary_name
+    binary=$(</etc/pihole/ftlbinary)
```
Comment (dschaper) [inline advanced/Scripts/piholeCheckout.sh]: How does this work if the file is not in that directory anymore and is just available during binary download?

**Comment by PromoFaux** [comment]
Note to anyone reviewing this. We're going to ignore Codefactor.

**Comment by DL6ER** [comment]
It this still up-to-date (see PR description)?

> Binary name is stored in a temporary file in the download directory.

**Comment by PromoFaux** [comment]
Oh... no. We changed tactic half way through! It's now done with variables

**Comment by dschaper** [comment]
It's an intermediary fix. I think the issue was partially from setting values inside subshells and also shadowing variable names. There's room to improve more but this works and gets a fix to users now.

**Comment by PromoFaux** [comment]
some admincrimes will be needed 
image

File: automated install/basic-install.sh [hunk 2]
```diff
@@ -2219,6 +2219,9 @@ FTLinstall() {
         ftlBranch="master"
     fi
 
+    local binary
+    binary="${1}"
```
Comment (dschaper) [inline automated install/basic-install.sh]: This probably should throw an error of some type if `$1` is empty. Either error here or pass a retval to the caller to signal failure.
