### PR TITLE
Fix `pihole -v` output if WebAdmin not installed

### LINKED ISSUE #4279: `pihole -v -f -c` error if WebAdmin not installed, due to scripts under `/opt/pihole` not agreeing with each other
```
$ sudo rm /etc/pihole/GitHubVersions 
$ pihole -v -p
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
$ pihole -v -a
  AdminLTE version is -1 (Latest: v5.5.1)
$ pihole -v -f
  FTL version is v5.8.1 (Latest: v5.8.1)
$ sudo /opt/pihole/updatecheck.sh x remote
$ pihole -v -p
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
$ pihole -v -a
  AdminLTE version is -1 (Latest: v5.8.1)
$ pihole -v -f
  Current FTL version is v5.8.1.
$ pihole -v -f -l
  Invalid Option! Try 'pihole -v --help' for more information.
$ 
```

### PR DESCRIPTION
**Pull request by subnut**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---

Closes #4279

### CODE REVIEW

File: advanced/Scripts/version.sh [hunk 1]
```diff
@@ -91,11 +91,19 @@ getRemoteVersion(){
...
-        case $daemon in
-          "pi-hole"   )  echo "${arrCache[0]}";;
-          "AdminLTE"  )  echo "${arrCache[1]}";;
-          "FTL"       )  echo "${arrCache[2]}";;
-        esac
+
+        if [[ "${INSTALL_WEB_INTERFACE}" == true ]]; then
+            case $daemon in
+                "pi-hole"   )  echo "${arrCache[0]}";;
+                "AdminLTE"  )  echo "${arrCache[1]}";;
```
Comment (PromoFaux) [inline advanced/Scripts/version.sh:98]: How about something like this to reduce a duplication of the case statement below?

```suggestion
                "AdminLTE"  ) [[ "${INSTALL_WEB_INTERFACE}" == true ]] && echo "${arrCache[1]}";;
```

File: advanced/Scripts/version.sh [hunk 2]
```diff
@@ -140,6 +148,11 @@ getLocalBranch(){
 }
 
 versionOutput() {
+    [[ "$1" == "AdminLTE" ]] && [[ "${INSTALL_WEB_INTERFACE}" != true ]] && {
+        echo "  WebAdmin not installed"
+        return 1
+    }
+
```
Comment (MichaIng) [inline advanced/Scripts/version.sh:155]:
```suggestion
    if [[ "$1" == "AdminLTE" && "${INSTALL_WEB_INTERFACE}" != true ]]; then
        echo "  WebAdmin not installed"
        return 1
    fi
```
Mostly to comply with coding standards and to not have an >0 "exit" code when the conditions are not met (e.g. to allow `set -e` in the future)🙂.

**Comment by yubiuser** [comment]
Are you going to continue work on this PR?

**Comment by subnut** [comment]
Sorry, I've been AFK for a month due to technical and health related issues.

Will try to update this PR with the signed-off commits this week.

**Comment by subnut** [comment]
@yubiuser Done

**Review by MichaIng — APPROVED** [review]

**Comment by yubiuser** [comment]
Could you show that it actually fixes [#4730](https://github.com/pi-hole/pi-hole/issues/4279)? I esp. wonder about including `${INSTALL_WEB_INTERFACE}` when `setupVars` is only sourced in case of `defaultOutput`

**Comment by MichaIng** [comment]
Good find about `setupVars`. Should be find to source them on every call. The only case where they are currently not required (after this PR) is for `--help`.

**Comment by subnut** [comment]
On a freshly installed setup -
```
pi4@pi4:/opt/pihole $ ./version.sh -f -l
  Latest FTL version is v5.11
pi4@pi4:/opt/pihole $ sudo ./updatecheck.sh x remote
pi4@pi4:/opt/pihole $ ./version.sh -f -l
  Invalid Option! Try 'pihole -v --help' for more information.
pi4@pi4:/opt/pihole $ sudo cp ~/pi-hole/advanced/Scripts/version.sh version.sh.new
pi4@pi4:/opt/pihole $ ./version.sh.new -f -l
  Latest FTL version is v5.11
pi4@pi4:/opt/pihole $ 
```

Seems to be working.

**Comment by subnut** [comment]
@yubiuser @MichaIng Anything else needs to be checked? Or is this PR ready to be merged?

**Comment by MichaIng** [comment]
@subnut 
As noted by yubiuser, please move `source /etc/pihole/setupVars.conf` from `defaultOutput()` to be loaded in every case, e.g. above `case "${1}" in` (main input handler). Else `versionOutput()` does not have `INSTALL_WEB_INTERFACE` loaded when using     `-p`/`--pihole`/`-a`/`--admin`/`-f`/`--ftl` arguments.

**Comment by subnut** [comment]
Lemme know if any changes are needed :)

**Comment by MichaIng** [comment]
> What's this?

On Pi-hole, whenever a commit is done to a PR, all reviews are dismissed. Basically reasonable since maintainers may want to assure that the changes done with the new commit are reviewed as well before it can be merged. We do it the same way, though default on GitHub is that commits do not dismiss new commits, which I find a strange default, tbh 😄.

Now it should work fine 👍.

**Review by DL6ER — APPROVED** [review]

File: pihole [hunk 3]
```diff
@@ -95,8 +95,7 @@ uninstallFunc() {
 
 versionFunc() {
   shift
-  "${PI_HOLE_SCRIPT_DIR}"/version.sh "$@"
-  exit 0
+  exec "${PI_HOLE_SCRIPT_DIR}"/version.sh "$@"
```
Comment (yubiuser) [inline pihole:98]: Is there a special reason to use `exec` here?

```suggestion
  "${PI_HOLE_SCRIPT_DIR}"/version.sh "$@"
  exit $?
```

Comment (MichaIng) [reply pihole:98]: This is to provide an exit code, so that `return 1` in the functions/`exit 1` in `version.sh` also leads to an `exit 1` of the `pihole` command. `exit $?` is the obvious alternative.

The "benefit" of `exec` is that it replaces the invoking process instead of spawning a child. So there are no two processes running but only one, less overhead and one does not need to pass the exit code from the child to the parent. So if a command is assured to be the last command in a script, `exec` simply always makes sense.

Comment (yubiuser) [reply pihole:98]: Then we should probably change it here too

https://github.com/pi-hole/pi-hole/blob/b5e0f142ccefe9b1b59b94d7e82d3052efbfdcd0/pihole#L73-L75


But this is for another PR

**Comment by yubiuser** [comment]
Going to squash merge, even if DCO is complaining. Only the last commit was not signed, but all previous. The squash merge should contain the sign-off line.
