### PR TITLE
Add a new migration script to fix the previous one

### LINKED ISSUE #3059: Dev branch: Error: no such table: main.group__ on `pihole -g`
First of all, I apologize if this is on the wrong repo.

**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`pihole -g runs fine and finishes updating lists`

**Actual behaviour:**

`  [i] Neutrino emissions detected...
  [✗] Pulling blocklist source list into range
  [i] No source list found, or it is empty

Error: no such table: main.group__
Error: no such table: main.group__
  [i] Number of gravity domains:  ( unique domains)
Error: no such table: main.group__
  [i] Number of exact blacklisted domains:
Error: no such table: main.group__
  [i] Number of regex blacklist filters:
Error: no such table: main.group__
  [i] Number of exact whitelisted domains:
Error: no such table: main.group__
  [i] Number of regex whitelist filters:
  [✓] Cleaning up stray matter

  [✓] Flushing DNS cache
  [✗] DNS service is NOT running`

**Steps to reproduce:**

`Update to latest dev commits (at which point it should fail gravity already)`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`8rsz9gitpg`

**Troubleshooting undertaken, and/or other relevant information:**

`pihole -r and reconfiguring, reverting to master makes it work again`

**Additional info:**
I can reproduce this on both my OrangePi Zero, and my "redundant" VM in FreeNAS. Both run Debian 10 converted to DietPi, **however** I used the original install script of PiHole, and not from dietpi-software.

### PR DESCRIPTION
**Pull request by PromoFaux**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**
Fixes #3059

Sort out some database modifications that slipped us by. Confirmed working by @technicalpyro

### CODE REVIEW

File: advanced/Scripts/database_migration/gravity/8_to_9.sql [hunk 1]
```diff
@@ -22,5 +22,6 @@ CREATE TRIGGER tr_group_zero AFTER DELETE ON "group"
       INSERT OR IGNORE INTO "group" (id,enabled,name) VALUES (0,1,'Unassociated');
     END;
 
+UPDATE info SET value = 9 WHERE property = 'version';
```
Comment (PromoFaux) [inline advanced/Scripts/database_migration/gravity/8_to_9.sql]: Whoops! 😟
